# Generated by Django 3.2.3 on 2021-07-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryspeed',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(choices=[('ORDINARY', 'ORDINARY'), ('EXPRESS', 'EXPRESS')], default='ORDINARY', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.location'),
        ),
        migrations.DeleteModel(
            name='DeliverySpeed',
        ),
    ]
