# Generated by Django 3.2.3 on 2021-07-10 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210710_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(blank=True, default=5000, null=True, validators=[django.core.validators.MinValueValidator(500)]),
        ),
    ]
