# Generated by Django 3.2.3 on 2021-07-15 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total_amount',
            field=models.IntegerField(blank=True, default=500, null=True, validators=[django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('mobile money', 'mobile money'), ('card', 'card')], default='cash', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('paid', 'paid'), ('expired', 'expired')], default='pending', max_length=30, null=True),
        ),
    ]
