# Generated by Django 3.2.3 on 2021-07-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210715_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='phone_number',
            new_name='momo_phone_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('vehicle', 'vehicle'), ('motorcycle', 'motorcycle'), ('pickup', 'pickup')], default='motorcycle', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(choices=[('ordinary', 'ordinary'), ('express', 'express')], default='ordinary', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('placed', 'placed'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('delivered', 'delivered')], default='placed', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('momo', 'momo'), ('card', 'card')], default='cash', max_length=30, null=True),
        ),
    ]
