# Generated by Django 3.2.3 on 2021-08-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_location_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metric',
            field=models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('p', 'p'), ('bunch', 'bunch')], default='kg', max_length=30),
        ),
    ]
