# Generated by Django 3.2.3 on 2021-07-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('mobile money', 'mobile money'), ('card', 'card')], default='cash', max_length=30, null=True),
        ),
    ]
