# Generated by Django 3.2.3 on 2021-08-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metric',
            field=models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('piece', 'piece'), ('bunch', 'bunch')], default='kg', max_length=30),
        ),
    ]
