# Generated by Django 3.2.3 on 2021-07-15 13:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_tracking_number',
            field=models.CharField(blank=True, default=app.models.generate_random_token, max_length=30, null=True),
        ),
    ]
