# Generated by Django 3.2.3 on 2021-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/curated/'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_curated_list',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
