from .announcement_test import *
from .announcementSerializer_test import *
from .category_test import *
from .categorySerializer_test import *
from .deliverySpeed_test import *
from .deliverySpeedSerializer_test import *
from .district_test import *
from .districtSerializer_test import *
from .location_test import *
from .locationSerializer_test import *
from .order_test import *
from .orderItem_test import *
from .orderItemSerializer_test import *
from .orderSerializer_test import *
from .payment_test import *
from .paymentSerializer_test import *
from .product_test import *
from .productSerializer_test import *
from .shop_test import *
from .shopSerializer_test import *
from .stock_test import *
from .stockSerializer_test import *
from .user_test import *
from .userSerializer_test import *
